#!/usr/bin/env python3
"""Convert a Russian frequency-list PDF into an Anki deck with TTS audio
and optional LLM-generated usage notes.

Expected PDF layout:

    1 - И [i] - And
    Вчера она купила фрукты и овощи.
    She bought some fruit and vegetables yesterday.

Audio is generated online with Microsoft Edge TTS using the Russian male
voice ``ru-RU-DmitryNeural`` by default.  Each note produces two Anki cards:
Russian -> English and English -> Russian, and each includes both a
normal-speed and a slowed-down clip of the Russian example sentence.

Optional usage notes are generated by a locally-running Ollama model
(default: llama3.1:8b).  Notes are opt-in via --llm ollama and are cached
under --llm-cache-dir just like TTS audio.

Install:
    python3 -m pip install pdfplumber genanki edge-tts

Optional, for --llm ollama:
    - Install Ollama:   https://ollama.com/download
    - Pull a model:     ollama pull llama3.1:8b
    - Start the server: ollama serve

Self-tests (no PDF, no network, no Ollama required):
    python3 pdf_to_anki_edge.py --self-test
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import html
import json
import re
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from html.parser import HTMLParser
from pathlib import Path
from typing import Callable, Optional

__version__ = "12.0.0"

# --- Optional dependencies ---------------------------------------------------

try:
    import pdfplumber
except ImportError:
    pdfplumber = None

try:
    import genanki
except ImportError:
    genanki = None

try:
    import edge_tts
except ImportError:
    edge_tts = None


# --- Errors ------------------------------------------------------------------

class ConversionError(Exception):
    """Base for expected, user-facing failures."""


class ParsingError(ConversionError):
    pass


class TTSError(ConversionError):
    pass


class LLMError(ConversionError):
    pass


# --- Regex / constants -------------------------------------------------------

HEADER_RE = re.compile(
    r"^\s*(?P<rank>\d+)\s*[-–—]\s*"
    r"(?P<word>.+?)\s*"
    r"\[(?P<pron>.*?)\]\s*"
    r"[-–—]\s*"
    r"(?P<translation>.+?)\s*$"
)
CYRILLIC_RE = re.compile(r"[\u0400-\u04FF]")
LATIN_RE = re.compile(r"[A-Za-z]")

MIN_SPLIT_WORDS = 2
MIN_SPLIT_WORDS_SHORT = 1
TERMINAL_PUNCT = ".!?…"


# --- Text helpers ------------------------------------------------------------

def classify_word(word: str) -> str:
    cyr = len(CYRILLIC_RE.findall(word))
    lat = len(LATIN_RE.findall(word))
    if cyr == 0 and lat == 0:
        return "neutral"
    return "ru" if cyr > lat else "en"


def _ends_terminal(word: str) -> bool:
    return bool(word) and word[-1] in TERMINAL_PUNCT


def split_bilingual_line(line: str) -> tuple[Optional[str], Optional[str]]:
    """Split a merged RU/EN line, or (None, None) if it isn't bilingual."""
    words = line.split()
    if len(words) < 2:
        return None, None
    classes = [classify_word(w) for w in words]

    for i in range(1, len(words)):
        head = [c for c in classes[:i] if c != "neutral"]
        tail = [c for c in classes[i:] if c != "neutral"]
        if not head or not tail:
            continue
        if not (all(c == "ru" for c in head) and all(c == "en" for c in tail)):
            continue

        short_ok = (
            len(head) >= MIN_SPLIT_WORDS_SHORT
            and len(tail) >= MIN_SPLIT_WORDS_SHORT
            and _ends_terminal(words[i - 1])
            and _ends_terminal(words[-1])
        )
        normal_ok = len(head) >= MIN_SPLIT_WORDS and len(tail) >= MIN_SPLIT_WORDS
        if short_ok or normal_ok:
            return " ".join(words[:i]).strip(), " ".join(words[i:]).strip()

    return None, None


class _TagStripper(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self._parts: list[str] = []

    def handle_data(self, data: str) -> None:
        self._parts.append(data)

    def get_text(self) -> str:
        return "".join(self._parts)


def strip_tags(text: str) -> str:
    if not text:
        return text
    parser = _TagStripper()
    try:
        parser.feed(text)
        parser.close()
        return parser.get_text()
    except Exception:
        return re.sub(r"</?b>", "", text)


def bold_word_in_sentence(sentence: str, word: str) -> str:
    """Bold first exact occurrence of `word`, HTML-safe."""
    if not sentence or not word:
        return html.escape(sentence or "")
    escaped = html.escape(sentence)
    escaped_word = html.escape(word)
    pattern = re.compile(
        r"(?<!\w)(" + re.escape(escaped_word) + r")(?!\w)",
        flags=re.IGNORECASE | re.UNICODE,
    )
    return pattern.sub(r"<b>\1</b>", escaped, count=1)


# --- PDF parsing -------------------------------------------------------------

def extract_text(pdf_path: str) -> str:
    if pdfplumber is None:
        raise ParsingError(
            "pdfplumber is not installed. Install with:\n"
            "  python3 -m pip install pdfplumber"
        )
    chunks = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            chunks.append(page.extract_text() or "")
    return "\n\n".join(chunks)


def parse_entries(raw_text: str, debug: bool = False) -> list[dict]:
    entries: list[dict] = []
    current: Optional[dict] = None

    for raw_line in raw_text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        match = HEADER_RE.match(line)
        if match:
            if current:
                entries.append(current)
            current = {
                "rank": match.group("rank"),
                "word": match.group("word").strip(),
                "pronunciation": match.group("pron").strip(),
                "translation": match.group("translation").strip(),
                "example_ru": "",
                "example_en": "",
            }
            continue

        if current is None:
            continue

        cyr_count = len(CYRILLIC_RE.findall(line))
        lat_count = len(LATIN_RE.findall(line))

        translation_unbalanced = (
            current["translation"].count("(") > current["translation"].count(")")
        )
        translation_still_incomplete = (
            not current["example_ru"] and lat_count > 0 and lat_count >= cyr_count
        )

        if translation_unbalanced:
            current["translation"] = (current["translation"] + " " + line).strip()
            if debug:
                _debug_line(line, "TRANSLATION CONTINUATION (closing paren)",
                            translation=current["translation"])
            continue

        ru_part, en_part = split_bilingual_line(line)
        if ru_part is not None:
            current["example_ru"] = (
                (current["example_ru"] + " " + ru_part).strip()
                if current["example_ru"] else ru_part
            )
            current["example_en"] = (
                (current["example_en"] + " " + en_part).strip()
                if current["example_en"] else en_part
            )
            if debug:
                _debug_line(line, "BILINGUAL (split found)",
                            example_ru=ru_part, example_en=en_part)
            continue

        if translation_still_incomplete:
            current["translation"] = (current["translation"] + " " + line).strip()
            if debug:
                _debug_line(line, "TRANSLATION CONTINUATION (no RU example yet)",
                            translation=current["translation"])
            continue

        field = "example_ru" if cyr_count > lat_count else "example_en"
        current[field] = (
            (current[field] + " " + line).strip() if current[field] else line
        )
        if debug:
            _debug_line(
                line,
                f"single-language ({'Russian' if field == 'example_ru' else 'English'})",
                **{field: line, "_counts": (cyr_count, lat_count)},
            )

    if current:
        entries.append(current)
    return entries


def _debug_line(raw: str, verdict: str, **fields) -> None:
    print(f"Raw extracted line:\n  {raw}")
    print(f"Detected: {verdict}")
    counts = fields.pop("_counts", None)
    if counts:
        print(f"  Cyrillic chars: {counts[0]}   Latin chars: {counts[1]}")
    for k, v in fields.items():
        print(f"  Parsed {k}: {v}")
    print()


# --- Entry cleaning ----------------------------------------------------------

def normalize_word(word: str) -> str:
    return word.strip().lower().rstrip(".,;:!?")


def clean_entries(raw_entries: list[dict]) -> list[dict]:
    cleaned = []
    for entry in raw_entries:
        word = normalize_word(entry["word"])
        cleaned.append({
            "rank": str(entry["rank"]),
            "word": word,
            "pronunciation": entry["pronunciation"].strip(),
            "translation": entry["translation"].strip(),
            "example_ru": bold_word_in_sentence(entry["example_ru"].strip(), word),
            "example_en": entry["example_en"].strip(),
        })
    return cleaned


def rank_int_or_none(entry: dict) -> Optional[int]:
    try:
        return int(entry["rank"])
    except (ValueError, TypeError):
        return None


def assign_sequence(entries: list[dict]) -> list[str]:
    mismatches = []
    for i, entry in enumerate(entries, start=1):
        entry["seq"] = i
        entry["rank_int"] = rank_int_or_none(entry)
        if entry["rank_int"] != i:
            mismatches.append(entry["rank"])
    return mismatches


def find_mixed_language_entries(entries: list[dict]) -> list[str]:
    flagged = []
    for entry in entries:
        for field, expected in (("example_ru", "ru"), ("example_en", "en")):
            text = strip_tags(entry[field])
            if not text:
                continue
            cyr = len(CYRILLIC_RE.findall(text))
            lat = len(LATIN_RE.findall(text))
            if expected == "ru" and lat > 0 and lat >= cyr:
                flagged.append(f"#{entry['rank']} ({field})")
                break
            if expected == "en" and cyr > 0 and cyr >= lat:
                flagged.append(f"#{entry['rank']} ({field})")
                break
    return flagged


def find_unbolded_entries(entries: list[dict]) -> list[str]:
    flagged = []
    for entry in entries:
        if entry["word"] and entry["example_ru"] and "<b>" not in entry["example_ru"]:
            flagged.append(entry["rank"])
    return flagged


def select_by_rank_range(
    entries: list[dict], start: Optional[int], end: Optional[int]
) -> tuple[list[dict], int, int]:
    numeric = [e["rank_int"] for e in entries if e["rank_int"] is not None]
    if not numeric:
        raise ParsingError("No entries have a usable numeric rank; can't apply --start/--end.")
    min_rank, max_rank = min(numeric), max(numeric)
    lo = start if start is not None else min_rank
    hi = end if end is not None else max_rank

    selected = [
        e for e in entries if e["rank_int"] is not None and lo <= e["rank_int"] <= hi
    ]

    print(f"Requested range: {lo}-{hi}")
    print(f"Available entries: {min_rank}-{max_rank}")
    if selected:
        sel_lo = min(e["rank_int"] for e in selected)
        sel_hi = max(e["rank_int"] for e in selected)
        print(f"Selected entries: {sel_lo}-{sel_hi} "
              f"({len(selected)} entries, {len(selected) * 2} cards)")
    else:
        print("Selected entries: none (requested range doesn't overlap the available data)")
    return selected, lo, hi


# --- Preview deck ------------------------------------------------------------

PREVIEW_ENTRIES = [
    {"rank": "1", "word": "И", "pronunciation": "i", "translation": "And",
     "example_ru": "Вчера она купила фрукты и овощи.",
     "example_en": "She bought some fruit and vegetables yesterday."},
    {"rank": "2", "word": "В", "pronunciation": "v", "translation": "In, on, at",
     "example_ru": "Маленький котёнок спрятался в подвале.",
     "example_en": "A little kitten hid in the basement."},
    {"rank": "3", "word": "Не", "pronunciation": "nje", "translation": "Not, no",
     "example_ru": "Я не люблю дождливую погоду.",
     "example_en": "I do not like rainy weather."},
    {"rank": "4", "word": "Он", "pronunciation": "on", "translation": "He",
     "example_ru": "Он очень хороший друг.",
     "example_en": "He is a very good friend."},
    {"rank": "5", "word": "На", "pronunciation": "na", "translation": "On, at",
     "example_ru": "Книга лежит на столе.",
     "example_en": "The book is lying on the table."},
]


# --- TTS backends ------------------------------------------------------------

RHVOICE_VOICES = [
    "Aleksandr-hq", "Aleksandr", "Anna", "Arina", "Artemiy", "Elena",
    "Evgeniy-Rus", "Irina", "Mikhail", "Pavel", "Tatiana", "Victoria",
    "Vitaliy", "Yuriy",
]

ESPEAK_BASE_WPM = 140


def speed_to_edge_rate(speed_pct: int) -> str:
    return f"{speed_pct - 100:+d}%"


def speed_to_rhvoice_rate(speed_pct: int) -> int:
    return speed_pct


def speed_to_espeak_wpm(speed_pct: int) -> int:
    return max(10, round(ESPEAK_BASE_WPM * speed_pct / 100))


def pick_tts_engine(requested: str) -> str:
    have_edge = edge_tts is not None
    have_rhvoice = shutil.which("RHVoice-test") is not None
    have_espeak = shutil.which("espeak-ng") is not None

    if requested == "edge":
        if not have_edge:
            raise TTSError("edge-tts is not installed. Install with:\n"
                           "  python3 -m pip install edge-tts")
        return "edge"
    if requested == "rhvoice":
        if not have_rhvoice:
            raise TTSError("RHVoice-test is not installed. On Linux Mint/Ubuntu:\n"
                           "  sudo apt install rhvoice rhvoice-russian ffmpeg")
        return "rhvoice"
    if requested == "espeak":
        if not have_espeak:
            raise TTSError("espeak-ng is not installed. On Linux Mint/Ubuntu:\n"
                           "  sudo apt install espeak-ng ffmpeg")
        return "espeak"

    if have_edge:
        return "edge"
    if have_rhvoice:
        return "rhvoice"
    if have_espeak:
        return "espeak"
    raise TTSError("No TTS engine is available. Install edge-tts, RHVoice, or eSpeak NG.")


def check_audio_dependencies(engine: str) -> None:
    if engine != "edge" and shutil.which("ffmpeg") is None:
        raise TTSError("ffmpeg is required for RHVoice/eSpeak MP3 conversion.\n"
                       "On Linux Mint/Ubuntu:\n  sudo apt install ffmpeg")


def resolve_voice(engine: str, requested_voice: Optional[str]) -> str:
    if engine == "edge":
        return requested_voice or "ru-RU-DmitryNeural"
    if engine == "rhvoice":
        voice = requested_voice or "Anna"
        match = next((v for v in RHVOICE_VOICES if v.lower() == voice.lower()), None)
        if match is None:
            raise TTSError(f"Unknown RHVoice voice '{voice}'. Options: "
                           + ", ".join(RHVOICE_VOICES))
        return match
    return requested_voice or "ru"


def resolve_speeds(args: argparse.Namespace, engine: str) -> tuple:
    if args.speed is not None:
        print(f"Note: --speed {args.speed} overrides the engine-specific rate flag for this run.")
        if engine == "edge":
            normal = speed_to_edge_rate(args.speed)
        elif engine == "rhvoice":
            normal = speed_to_rhvoice_rate(args.speed)
        else:
            normal = speed_to_espeak_wpm(args.speed)
    else:
        if engine == "edge":
            normal = args.edge_rate
        elif engine == "rhvoice":
            normal = args.rhvoice_rate
        else:
            normal = args.tts_speed

    if args.slow_speed is not None:
        print(f"Note: --slow-speed {args.slow_speed} overrides the engine-specific slow-rate behavior for this run.")
        if engine == "edge":
            slow = speed_to_edge_rate(args.slow_speed)
        elif engine == "rhvoice":
            slow = speed_to_rhvoice_rate(args.slow_speed)
        else:
            slow = speed_to_espeak_wpm(args.slow_speed)
    else:
        if engine == "edge":
            slow = args.slow_rate
        elif engine == "rhvoice":
            base = args.rhvoice_rate
            slow = max(10, base // 2)
            if slow == base:
                print(f"Note: RHVoice slow rate clamped to {slow}% (was {base // 2}%).")
        else:
            base_wpm = args.tts_speed
            slow = max(40, base_wpm // 2)
            if slow >= base_wpm:
                slow = max(10, base_wpm - 10)
                print(f"Note: eSpeak slow rate clamped to {slow} wpm "
                      f"(was {base_wpm // 2}, which is not slower than normal).")

    return normal, slow


def _wav_to_mp3(wav_path: Path, out_mp3_path: Path, bitrate: str = "96k") -> bool:
    result = subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-i", str(wav_path),
         "-codec:a", "libmp3lame", "-b:a", bitrate, str(out_mp3_path)],
        capture_output=True, text=True,
    )
    return (result.returncode == 0
            and out_mp3_path.exists()
            and out_mp3_path.stat().st_size > 0)


def synthesize_text_audio_edge(
    text: str, out_mp3_path: Path, voice: str,
    rate: str = "+0%", pitch: str = "+0Hz",
    retries: int = 3, retry_delay: float = 1.5,
) -> bool:
    last_exc: Optional[BaseException] = None
    for attempt in range(1, retries + 1):
        try:
            comm = edge_tts.Communicate(text=text, voice=voice, rate=rate, pitch=pitch)
            comm.save_sync(str(out_mp3_path))
            if out_mp3_path.exists() and out_mp3_path.stat().st_size > 0:
                return True
            last_exc = RuntimeError("no audio received (empty file)")
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
        out_mp3_path.unlink(missing_ok=True)
        if attempt < retries:
            time.sleep(retry_delay)
    print(f"Edge TTS error for {text!r} after {retries} attempts: {last_exc}",
          file=sys.stderr)
    return False


def synthesize_text_audio_rhvoice(
    text: str, out_mp3_path: Path, voice: str,
    rate: int = 100, pitch: int = 100, mp3_bitrate: str = "96k",
) -> bool:
    with tempfile.NamedTemporaryFile(suffix=".txt", mode="w", delete=False,
                                     encoding="utf-8") as tmp_txt:
        tmp_txt.write(text)
        txt_path = Path(tmp_txt.name)
    wav_path = txt_path.with_suffix(".wav")
    try:
        result = subprocess.run(
            ["RHVoice-test", "-p", voice, "-R", "24000",
             "-r", str(rate), "-t", str(pitch),
             "-i", str(txt_path), "-o", str(wav_path)],
            capture_output=True, text=True, timeout=20,
        )
        if result.returncode != 0 or not wav_path.exists() or wav_path.stat().st_size == 0:
            return False
        return _wav_to_mp3(wav_path, out_mp3_path, mp3_bitrate)
    except subprocess.TimeoutExpired:
        return False
    finally:
        txt_path.unlink(missing_ok=True)
        wav_path.unlink(missing_ok=True)


def synthesize_text_audio_espeak(
    text: str, out_mp3_path: Path, voice: str, speed: int, mp3_bitrate: str = "96k",
) -> bool:
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp_wav:
        wav_path = Path(tmp_wav.name)
    try:
        result = subprocess.run(
            ["espeak-ng", "-v", voice, "-s", str(speed), "-w", str(wav_path), text],
            capture_output=True, text=True,
        )
        if result.returncode != 0 or not wav_path.exists() or wav_path.stat().st_size == 0:
            return False
        return _wav_to_mp3(wav_path, out_mp3_path, mp3_bitrate)
    finally:
        wav_path.unlink(missing_ok=True)


def synthesize_text_audio(
    text: str, out_mp3_path: Path, engine: str, voice: str, rate_value,
    edge_pitch: str, rhvoice_pitch: int, mp3_bitrate: str,
    edge_retries: int = 3, edge_retry_delay: float = 1.5,
) -> bool:
    if engine == "edge":
        return synthesize_text_audio_edge(
            text, out_mp3_path, voice=voice, rate=rate_value, pitch=edge_pitch,
            retries=edge_retries, retry_delay=edge_retry_delay,
        )
    if engine == "rhvoice":
        return synthesize_text_audio_rhvoice(
            text, out_mp3_path, voice=voice, rate=rate_value,
            pitch=rhvoice_pitch, mp3_bitrate=mp3_bitrate,
        )
    return synthesize_text_audio_espeak(
        text, out_mp3_path, voice=voice, speed=rate_value, mp3_bitrate=mp3_bitrate,
    )


# --- Audio caching + orchestration -------------------------------------------

def slugify(text: str, max_len: int = 24) -> str:
    text = re.sub(r"[^\w]+", "_", text.strip().lower(), flags=re.UNICODE).strip("_")
    return text[:max_len] or "x"


def pitch_repr_for_cache(engine: str, edge_pitch: str, rhvoice_pitch: int) -> str:
    if engine == "edge":
        return edge_pitch
    if engine == "rhvoice":
        return str(rhvoice_pitch)
    return "na"


def cache_key_for(engine: str, voice: str, rate_value, pitch_value: str, text: str) -> str:
    raw = f"{engine}|{voice}|{rate_value}|{pitch_value}|{text}"
    return hashlib.sha1(raw.encode("utf-8")).hexdigest()[:16]


def add_audio_to_entries(
    entries: list[dict], cache_dir: Path, engine: str, voice: str,
    normal_rate, slow_rate,
    edge_pitch: str, rhvoice_pitch: int, mp3_bitrate: str,
    edge_retries: int = 3, edge_retry_delay: float = 1.5,
    use_cache: bool = True,
    progress: Optional[Callable[[int, int, str], None]] = None,
) -> tuple[list[str], list[tuple[str, str, str]]]:
    media_files: list[str] = []
    failures: list[tuple[str, str, str]] = []
    cache_hits = 0
    cache_misses = 0
    pitch_repr = pitch_repr_for_cache(engine, edge_pitch, rhvoice_pitch)

    def get_or_make(clip_type: str, text: str, rate_value) -> Optional[Path]:
        nonlocal cache_hits, cache_misses
        key = cache_key_for(engine, voice, rate_value, pitch_repr, text)
        clip_dir = cache_dir / clip_type
        clip_dir.mkdir(parents=True, exist_ok=True)
        path = clip_dir / f"{slugify(text)}_{key}.mp3"

        if use_cache and path.exists() and path.stat().st_size > 0:
            cache_hits += 1
            return path

        ok = synthesize_text_audio(
            text, path, engine=engine, voice=voice, rate_value=rate_value,
            edge_pitch=edge_pitch, rhvoice_pitch=rhvoice_pitch,
            mp3_bitrate=mp3_bitrate,
            edge_retries=edge_retries, edge_retry_delay=edge_retry_delay,
        )
        cache_misses += 1
        return path if ok else None

    total = len(entries)
    for index, entry in enumerate(entries, start=1):
        if progress:
            progress(index, total, entry["word"])
        text_word = entry["word"]
        text_sentence = strip_tags(entry["example_ru"]).strip()

        if text_word:
            path = get_or_make("word", text_word, normal_rate)
            if path:
                entry["audio_tag"] = f"[sound:{path.name}]"
                media_files.append(str(path))
            else:
                entry["audio_tag"] = ""
                failures.append((entry["rank"], entry["word"], "word"))
        else:
            entry["audio_tag"] = ""

        if text_sentence:
            path = get_or_make("example", text_sentence, normal_rate)
            if path:
                entry["example_audio_tag"] = f"[sound:{path.name}]"
                media_files.append(str(path))
            else:
                entry["example_audio_tag"] = ""
                failures.append((entry["rank"], entry["word"], "sentence"))

            slow_path = get_or_make("example_slow", text_sentence, slow_rate)
            if slow_path:
                entry["example_audio_slow_tag"] = f"[sound:{slow_path.name}]"
                media_files.append(str(slow_path))
            else:
                entry["example_audio_slow_tag"] = ""
                failures.append((entry["rank"], entry["word"], "sentence_slow"))
        else:
            entry["example_audio_tag"] = ""
            entry["example_audio_slow_tag"] = ""

    print(f"  Cache: {cache_hits} reused, {cache_misses} generated")
    media_files = list(dict.fromkeys(media_files))
    return media_files, failures


def write_failed_log(path: Path, failures: list[tuple[str, str, str]]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        for rank, word, clip_type in failures:
            f.write(f"#{rank} {word} ({clip_type})\n")



# --- LLM usage notes ---------------------------------------------------------
#
# Design notes:
#
#  * The prompt is a versioned artifact.  USAGE_NOTE_PROMPT_VERSION is part of
#    the cache key, so bumping it after changing the prompt forces a clean
#    regeneration of every note.
#  * The cache key is (model, prompt_version, word, translation) - NOT the
#    example sentence, so tweaking an example doesn't regenerate every note.
#  * Generation is fail-per-entry: a single bad call appends to the failure
#    list rather than aborting the run.
#  * Ollama availability is checked ONCE, up front, with a clear error message
#    if the server isn't reachable - not once per entry.

USAGE_NOTE_PROMPT_VERSION = "1"

USAGE_NOTE_SYSTEM = (
    "You are a concise Russian-language tutor writing short usage notes for "
    "an English-speaking learner of Russian. You write plain prose in English, "
    "not bullet points, not markdown, not numbered lists. You are honest about "
    "uncertainty: if you are not confident about a grammatical or register "
    "claim, you omit it rather than guessing."
)

USAGE_NOTE_USER_TEMPLATE = (
    "Russian word: {word}\n"
    "Translation given: {translation}\n"
    "Example sentence (for disambiguation only): {example_ru}\n"
    "\n"
    "In 1 to 2 short sentences, describe how this Russian word is used in "
    "practice: its register (formal / neutral / colloquial), any common "
    "collocations, and at most ONE common point of confusion for English "
    "speakers (such as a false friend or a similarly-spelled word with a "
    "different meaning).\n"
    "\n"
    "Rules:\n"
    "- Do NOT repeat the translation verbatim.\n"
    "- Do NOT comment on the example sentence itself.\n"
    "- Do NOT add your own example sentences.\n"
    "- Do NOT use markdown, bullet points, or bold.\n"
    "- If you are not confident about a claim, omit it.\n"
    "- Maximum 2 sentences. Aim for 25-45 words total.\n"
)


def llm_cache_key_for(model: str, prompt_version: str, word: str, translation: str) -> str:
    raw = f"{model}|{prompt_version}|{word}|{translation}"
    return hashlib.sha1(raw.encode("utf-8")).hexdigest()[:16]


def check_ollama_available(host: str, model: str) -> None:
    """Fail fast with a clear message if Ollama isn't reachable / model missing."""
    url = f"{host.rstrip('/')}/api/tags"
    try:
        with urllib.request.urlopen(url, timeout=5) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise LLMError(
            f"Ollama is not reachable at {host}.\n"
            f"Start it with:  ollama serve\n"
            f"Underlying error: {exc}"
        ) from exc
    except Exception as exc:  # noqa: BLE001
        raise LLMError(f"Could not query Ollama at {host}: {exc}") from exc

    available = {m.get("name", "") for m in payload.get("models", [])}
    # Ollama reports names with an implicit ':latest' tag sometimes; accept either.
    if model not in available and f"{model}:latest" not in available:
        raise LLMError(
            f"Ollama is running at {host} but model '{model}' is not installed.\n"
            f"Pull it with:  ollama pull {model}\n"
            f"Installed models: {', '.join(sorted(available)) or '(none)'}"
        )


def _call_ollama(
    host: str, model: str, system: str, user: str,
    timeout: float, temperature: float, max_tokens: int,
) -> str:
    """Single blocking call to Ollama's /api/chat. Raises LLMError on failure."""
    url = f"{host.rstrip('/')}/api/chat"
    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "stream": False,
        "options": {
            "temperature": temperature,
            "num_predict": max_tokens,
        },
    }
    request = urllib.request.Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise LLMError(f"Ollama request failed: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise LLMError(f"Ollama returned malformed JSON: {exc}") from exc

    content = (payload.get("message") or {}).get("content", "").strip()
    if not content:
        raise LLMError("Ollama returned an empty response.")
    return content


def _sanitize_usage_note(note: str) -> str:
    """Strip markdown/HTML the model may have produced anyway, collapse
    whitespace, cap length.  We render as plain text in the card."""
    note = re.sub(r"</?[a-zA-Z][^>]*>", "", note)         # HTML tags
    note = re.sub(r"\*\*(.+?)\*\*", r"\1", note)          # **bold**
    note = re.sub(r"\*(.+?)\*", r"\1", note)              # *italic*
    note = re.sub(r"^\s*[-*•]\s+", "", note, flags=re.M)  # bullets
    note = re.sub(r"^\s*\d+\.\s+", "", note, flags=re.M)  # numbered lists
    note = re.sub(r"\s+", " ", note).strip()
    if len(note) > 400:
        note = note[:397].rstrip() + "..."
    return note


def generate_usage_notes(
    entries: list[dict],
    cache_dir: Path,
    model: str,
    host: str,
    prompt_version: str = USAGE_NOTE_PROMPT_VERSION,
    timeout: float = 60.0,
    temperature: float = 0.3,
    max_tokens: int = 120,
    use_cache: bool = True,
    progress: Optional[Callable[[int, int, str], None]] = None,
) -> list[tuple[str, str, str]]:
    """Populate entry['usage_note'] for every entry.

    Returns a list of failures as (rank, word, reason).  Failures are
    non-fatal: the entry's usage_note is left empty and generation
    continues with the next entry.
    """
    failures: list[tuple[str, str, str]] = []
    cache_hits = 0
    cache_misses = 0
    cache_dir.mkdir(parents=True, exist_ok=True)

    total = len(entries)
    for index, entry in enumerate(entries, start=1):
        word = entry["word"]
        translation = entry["translation"]

        if progress:
            progress(index, total, word)

        key = llm_cache_key_for(model, prompt_version, word, translation)
        cache_path = cache_dir / f"{slugify(word)}_{key}.json"

        if use_cache and cache_path.exists() and cache_path.stat().st_size > 0:
            try:
                with open(cache_path, "r", encoding="utf-8") as f:
                    cached = json.load(f)
                entry["usage_note"] = cached.get("note", "")
                cache_hits += 1
                continue
            except (json.JSONDecodeError, OSError):
                # Corrupt cache entry -> fall through and regenerate.
                pass

        # Build the prompt.  We strip tags from example_ru so we don't send
        # the model "<b>...</b>" markup.
        example_ru = strip_tags(entry.get("example_ru", "")).strip()
        user_prompt = USAGE_NOTE_USER_TEMPLATE.format(
            word=word,
            translation=translation,
            example_ru=example_ru or "(none)",
        )

        try:
            raw = _call_ollama(
                host=host, model=model,
                system=USAGE_NOTE_SYSTEM, user=user_prompt,
                timeout=timeout, temperature=temperature, max_tokens=max_tokens,
            )
            note = _sanitize_usage_note(raw)
            entry["usage_note"] = note
            cache_misses += 1

            with open(cache_path, "w", encoding="utf-8") as f:
                json.dump(
                    {
                        "note": note,
                        "model": model,
                        "prompt_version": prompt_version,
                        "word": word,
                        "translation": translation,
                        "raw": raw,
                    },
                    f, ensure_ascii=False, indent=2,
                )
        except LLMError as exc:
            entry["usage_note"] = ""
            failures.append((entry["rank"], word, str(exc)))

    print(f"  LLM cache: {cache_hits} reused, {cache_misses} generated")
    return failures


def write_llm_failed_log(path: Path, failures: list[tuple[str, str, str]]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        for rank, word, reason in failures:
            f.write(f"#{rank} {word} ({reason})\n")



# --- Anki deck construction --------------------------------------------------

# NOTE: bumping MODEL_ID creates a NEW note type in Anki and orphans existing
# cards on re-import. Only bump when templates/fields actually change.
# v12: added UsageNote field, so this was bumped from 1607392409.
MODEL_ID = 1607392410
DECK_ID = 2059852317

CARD_CSS = """
.card {
    font-family: Arial, sans-serif;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}
.pron { font-size: 15px; color: #555; margin-top: 6px; }
.example {
    font-size: 15px;
    margin-top: 14px;
    text-align: left;
    display: inline-block;
}
.example .en { color: #555; }
.example b { font-weight: 700; }
.usage-note {
    font-size: 14px;
    color: #666;
    font-style: italic;
    margin-top: 12px;
    padding-top: 8px;
    border-top: 1px solid #eee;
    text-align: left;
    display: inline-block;
    max-width: 32em;
}
.rank { font-size: 12px; color: #999; margin-top: 10px; }
.audio { margin-top: 8px; }
.audio-row { margin-top: 4px; }
"""

EXAMPLE_BLOCK = """{{#ExampleRU}}
<div class="example">
{{ExampleRU}}<br>
{{#ExampleAudioSlow}}
<div class="audio-row">🐢 {{ExampleAudioSlow}}</div>
{{/ExampleAudioSlow}}
{{#ExampleAudio}}
<div class="audio-row">🐇 {{ExampleAudio}}</div>
{{/ExampleAudio}}
<span class="en">{{ExampleEN}}</span>
</div>
{{/ExampleRU}}"""

USAGE_NOTE_BLOCK = """{{#UsageNote}}
<div class="usage-note">{{UsageNote}}</div>
{{/UsageNote}}"""

RANK_LINE = '<div class="rank">#{{Rank}} most frequent</div>'

RU_EN_QFMT = """
<div>{{Word}}</div>
<div class="audio">{{Audio}}</div>
"""

RU_EN_AFMT = (
    "{{FrontSide}}\n"
    '<hr id="answer">\n'
    '<div class="pron">Russian Pronunciation: [{{Pronunciation}}]</div>\n'
    "<div>{{Translation}}</div>\n"
    + EXAMPLE_BLOCK + "\n"
    + USAGE_NOTE_BLOCK + "\n"
    + RANK_LINE + "\n"
)

EN_RU_QFMT = """
<div>{{Translation}}</div>
"""

EN_RU_AFMT = (
    "{{FrontSide}}\n"
    '<hr id="answer">\n'
    "<div>{{Word}}</div>\n"
    '<div class="pron">Russian Pronunciation: [{{Pronunciation}}]</div>\n'
    '<div class="audio">{{Audio}}</div>\n'
    + EXAMPLE_BLOCK + "\n"
    + USAGE_NOTE_BLOCK + "\n"
    + RANK_LINE + "\n"
)


def build_model() -> "genanki.Model":
    if genanki is None:
        raise ConversionError(
            "genanki is not installed. Install with:\n"
            "  python3 -m pip install genanki"
        )
    return genanki.Model(
        MODEL_ID,
        "Russian Frequency (RU<->EN, Edge TTS)",
        fields=[
            {"name": "Word"},
            {"name": "Pronunciation"},
            {"name": "Translation"},
            {"name": "ExampleRU"},
            {"name": "ExampleEN"},
            {"name": "Rank"},
            {"name": "Audio"},
            {"name": "ExampleAudio"},
            {"name": "ExampleAudioSlow"},
            {"name": "UsageNote"},
        ],
        templates=[
            {"name": "Russian -> English", "qfmt": RU_EN_QFMT, "afmt": RU_EN_AFMT},
            {"name": "English -> Russian", "qfmt": EN_RU_QFMT, "afmt": EN_RU_AFMT},
        ],
        css=CARD_CSS,
    )


def build_deck(entries: list[dict], deck_name: str) -> "genanki.Deck":
    model = build_model()
    deck = genanki.Deck(DECK_ID, deck_name)
    for entry in entries:
        # Stable GUID: same (rank, word) re-imports as an UPDATE, not a
        # duplicate.  If you edit either the rank or the word in the source
        # PDF, Anki will treat the entry as new - that is intentional.
        note = genanki.Note(
            model=model,
            fields=[
                entry["word"],
                entry["pronunciation"],
                entry["translation"],
                entry["example_ru"],
                entry["example_en"],
                entry["rank"],
                entry.get("audio_tag", ""),
                entry.get("example_audio_tag", ""),
                entry.get("example_audio_slow_tag", ""),
                entry.get("usage_note", ""),
            ],
            guid=genanki.guid_for(entry["rank"], entry["word"]),
        )
        deck.add_note(note)
    return deck


def write_csv(entries: list[dict], path: str) -> None:
    with open(path, "w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(
            csv_file,
            fieldnames=[
                "rank", "word", "pronunciation", "translation",
                "example_ru", "example_en",
                "audio_tag", "example_audio_tag", "example_audio_slow_tag",
                "usage_note",
            ],
            extrasaction="ignore",
        )
        writer.writeheader()
        writer.writerows(entries)


# --- CLI ---------------------------------------------------------------------

EPILOG = """
Examples
--------
First 100 words:
  python3 pdf_to_anki_edge.py words.pdf --first 100 -o first_100.apkg

Words 501-1000 (by the PDF's own printed rank number, not just position):
  python3 pdf_to_anki_edge.py words.pdf --start 501 --end 1000 -o 501_1000.apkg

Check a range and the parsed data BEFORE running any TTS (fast, no audio/file made):
  python3 pdf_to_anki_edge.py words.pdf --start 501 --end 1000 --dry-run

Test without audio (fast, no network/TTS needed):
  python3 pdf_to_anki_edge.py words.pdf --first 10 --no-audio -o test.apkg

Enable LLM usage notes (requires Ollama running locally):
  python3 pdf_to_anki_edge.py words.pdf --first 10 --llm ollama -o test.apkg

Generate a CSV backup alongside the deck:
  python3 pdf_to_anki_edge.py words.pdf --csv words.csv -o words.apkg

Simple cross-engine speed control (100 = normal speed, 75 = three-quarter speed):
  python3 pdf_to_anki_edge.py words.pdf --speed 100 --slow-speed 75

Force a fresh cache-free rebuild:
  python3 pdf_to_anki_edge.py words.pdf --no-cache --no-llm-cache

Mutually exclusive:
  --first          cannot be combined with --start/--end
  --preview        cannot be combined with a PDF path
  --speed          overrides --edge-rate / --rhvoice-rate / --tts-speed for this run
  --slow-speed     overrides --slow-rate / the auto half-rate for this run
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a Russian frequency PDF into an Anki audio deck.",
        epilog=EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--version", action="version", version=f"pdf_to_anki_edge {__version__}")
    parser.add_argument("pdf", nargs="?", help="Input PDF. Not required when --preview is used.")
    parser.add_argument("--preview", action="store_true",
                         help="Build the built-in five-word preview instead of reading a PDF.")
    parser.add_argument("--first", type=int, metavar="X", dest="first", default=None,
                         help="Use only the first X parsed words (by position, not rank).")
    parser.add_argument("--limit", type=int, metavar="X", dest="limit", default=None,
                         help="Deprecated alias for --first.")
    parser.add_argument("--start", type=int, metavar="N", default=None,
                         help="Only include words with PRINTED rank >= N (inclusive).")
    parser.add_argument("--end", type=int, metavar="N", default=None,
                         help="Only include words with PRINTED rank <= N (inclusive).")
    parser.add_argument("--dry-run", action="store_true",
                         help="Validate the PDF/range and print a summary, but generate no "
                              "audio, no notes, and write no files.")
    parser.add_argument("-o", "--output", default="russian_deck.apkg",
                         help="Output .apkg path (default: russian_deck.apkg).")
    parser.add_argument("--deck-name", default="Russian Most Frequent Words",
                         help="Name shown inside Anki.")
    parser.add_argument("--csv", help="Optional CSV backup path.")
    parser.add_argument("--no-audio", action="store_true",
                         help="Build cards without generating audio.")

    # --- TTS options ---
    parser.add_argument("--tts-engine", choices=["edge", "auto", "rhvoice", "espeak"],
                         default="edge",
                         help="TTS backend (default: edge). Edge is online.")
    parser.add_argument("--voice", help="Voice name. Edge default: ru-RU-DmitryNeural; "
                                         "RHVoice default: Anna; eSpeak default: ru.")
    parser.add_argument("--edge-rate", default="+0%",
                         help="Edge speaking rate, e.g. -10%% or +20%% (default: +0%%).")
    parser.add_argument("--edge-pitch", default="+0Hz",
                         help="Edge pitch, e.g. -10Hz or +10Hz (default: +0Hz).")
    parser.add_argument("--edge-retries", type=int, default=3,
                         help="Retry attempts for edge-tts's intermittent error (default: 3).")
    parser.add_argument("--edge-retry-delay", type=float, default=1.5,
                         help="Seconds between edge-tts retry attempts (default: 1.5).")
    parser.add_argument("--slow-rate", default="-50%",
                         help="Edge rate for the slow example-sentence clip (default: -50%%).")
    parser.add_argument("--tts-speed", type=int, default=140,
                         help="eSpeak speed in words/minute (default: 140).")
    parser.add_argument("--rhvoice-rate", type=int, default=100,
                         help="RHVoice speed, %% of normal (default: 100).")
    parser.add_argument("--rhvoice-pitch", type=int, default=100,
                         help="RHVoice pitch, %% of normal (default: 100).")
    parser.add_argument("--mp3-bitrate", default="96k",
                         help="mp3 bitrate for RHVoice/eSpeak output (default: 96k).")
    parser.add_argument("--speed", type=int, default=None,
                         help="Convenience: normal speaking speed as %% of default "
                              "(100=normal), same units for every engine. Overrides "
                              "--edge-rate/--rhvoice-rate/--tts-speed for this run only.")
    parser.add_argument("--slow-speed", type=int, default=None,
                         help="Convenience: speed for the slow example-sentence clip, "
                              "%% of default. Overrides --slow-rate / the auto half-rate "
                              "for this run only.")

    # --- Cache options ---
    parser.add_argument("--cache-dir", default="tts_cache",
                         help="Where generated audio is cached (default: ./tts_cache).")
    parser.add_argument("--no-cache", action="store_true",
                         help="Don't reuse cached audio (still writes new clips to the cache).")
    parser.add_argument("--failed-log", default=None,
                         help="Where to write the list of failed audio clips, if any "
                              "(default: <output>.failed.txt).")

    # --- LLM options ---
    parser.add_argument("--llm", choices=["none", "ollama"], default="none",
                         help="Enable LLM-generated usage notes via the named backend "
                              "(default: none). 'ollama' requires Ollama running locally.")
    parser.add_argument("--llm-model", default="llama3.1:8b",
                         help="Ollama model name (default: llama3.1:8b).")
    parser.add_argument("--llm-host", default="http://localhost:11434",
                         help="Ollama API endpoint (default: http://localhost:11434).")
    parser.add_argument("--llm-timeout", type=float, default=60.0,
                         help="Per-call timeout in seconds (default: 60).")
    parser.add_argument("--llm-temperature", type=float, default=0.3,
                         help="Sampling temperature (default: 0.3).")
    parser.add_argument("--llm-max-tokens", type=int, default=120,
                         help="Maximum tokens per usage note (default: 120).")
    parser.add_argument("--llm-cache-dir", default="llm_cache",
                         help="Where generated usage notes are cached (default: ./llm_cache).")
    parser.add_argument("--no-llm-cache", action="store_true",
                         help="Don't reuse cached usage notes (still writes new ones).")
    parser.add_argument("--llm-prompt-version", default=USAGE_NOTE_PROMPT_VERSION,
                         help="Prompt version for cache invalidation "
                              f"(default: {USAGE_NOTE_PROMPT_VERSION}).")
    parser.add_argument("--llm-failed-log", default=None,
                         help="Where to write the list of failed usage notes, if any "
                              "(default: <output>.llm_failed.txt).")

    # --- Debug options ---
    parser.add_argument("--debug-parse", action="store_true",
                         help="Print each raw extracted line during parsing, what was "
                              "detected, and the resulting field(s).")
    parser.add_argument("--self-test", action="store_true",
                         help="Run the built-in self-tests and exit.")

    args = parser.parse_args()

    # Reconcile --first / --limit (both mean "first N by position").
    if args.first is not None and args.limit is not None and args.first != args.limit:
        parser.error("use only one of --first or --limit (they mean the same thing)")
    if args.first is None and args.limit is not None:
        args.first = args.limit

    if not args.preview and not args.pdf:
        parser.error("provide a PDF path or use --preview")
    if args.preview and args.pdf:
        parser.error("use either a PDF path or --preview, not both")
    if args.first is not None and args.first < 1:
        parser.error("--first must be a positive integer")
    if args.first is not None and (args.start is not None or args.end is not None):
        parser.error("use either --first or --start/--end, not both")
    if args.start is not None and args.start < 1:
        parser.error("--start must be a positive integer")
    if args.end is not None and args.end < 1:
        parser.error("--end must be a positive integer")
    if args.start is not None and args.end is not None and args.start > args.end:
        parser.error("--start must be <= --end")
    if args.speed is not None and args.speed < 10:
        parser.error("--speed must be at least 10")
    if args.slow_speed is not None and args.slow_speed < 10:
        parser.error("--slow-speed must be at least 10")
    if args.llm == "none":
        # These are harmless to pass but do nothing; warn if a user looks
        # confused about whether notes will be generated.
        pass
    return args


# --- Main --------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    if args.self_test:
        sys.exit(_run_self_tests())

    if args.preview:
        raw_entries = [dict(entry) for entry in PREVIEW_ENTRIES]
        if args.deck_name == "Russian Most Frequent Words":
            args.deck_name = "Russian Frequency - 5 Word Preview"
        print("Using the built-in five-word preview.")
    else:
        if not Path(args.pdf).exists():
            raise ConversionError(f"File not found: {args.pdf}")
        print(f"Reading {args.pdf} ...")
        raw_entries = parse_entries(extract_text(args.pdf), debug=args.debug_parse)

    entries = clean_entries(raw_entries)
    if not entries:
        raise ParsingError("No entries were found. Check the PDF text layout.")
    total_entries = len(entries)
    print(f"PDF entries found: {total_entries}")

    rank_mismatches = assign_sequence(entries)
    if rank_mismatches:
        print(
            "Warning: printed rank number didn't match actual position in the PDF "
            "for these entries (--start/--end still use the PRINTED rank; a gap "
            "here means one of these numbers may not select what you expect): "
            + ", ".join(rank_mismatches[:20]),
            file=sys.stderr,
        )

    requested_lo = requested_hi = None
    if args.start is not None or args.end is not None:
        entries, requested_lo, requested_hi = select_by_rank_range(entries, args.start, args.end)
        if not entries:
            raise ParsingError("No entries fall within the requested --start/--end range.")
        if args.deck_name == "Russian Most Frequent Words":
            lo = min(e["rank_int"] for e in entries)
            hi = max(e["rank_int"] for e in entries)
            args.deck_name = f"Russian Most Frequent Words ({lo}-{hi})"
    elif args.first is not None:
        entries = entries[: args.first]
        print(f"Using {len(entries)} of {total_entries} entries ({len(entries) * 2} cards).")
    else:
        print(f"Selected entries: all {total_entries} ({total_entries * 2} cards).")

    entries.sort(key=lambda e: e["seq"])  # export order == frequency order

    missing_examples = [
        entry["rank"] for entry in entries if not entry["example_ru"] or not entry["example_en"]
    ]
    if missing_examples:
        print("Warning: entries missing an example: "
              + ", ".join(missing_examples[:20]), file=sys.stderr)

    mixed_language = find_mixed_language_entries(entries)
    if mixed_language:
        print(
            "Warning: these entries' examples still look like they're in the wrong "
            "language after parsing (likely leftover dictionary/footnote text) - "
            "worth checking manually: " + ", ".join(mixed_language[:20]),
            file=sys.stderr,
        )

    unbolded = find_unbolded_entries(entries)
    if unbolded:
        print(
            "Warning: target word not found verbatim in its example sentence "
            "(likely an inflected form) - not bolded on these cards: "
            + ", ".join(unbolded[:20]),
            file=sys.stderr,
        )

    # --- Dry run: stop before any TTS / LLM work -----------------------------
    if args.dry_run:
        print()
        print("Dry run - no audio or files were generated")
        print("-------------------------------------------")
        if requested_lo is not None:
            print(f"Requested range: {requested_lo}-{requested_hi}")
        elif args.first is not None:
            print(f"Requested: first {args.first} (via --first)")
        else:
            print("Requested range: (all)")
        print(f"Selected entries: {len(entries)}")
        print()
        print(f"Missing examples: {len(missing_examples)}")
        print(f"Mixed-language examples: {len(mixed_language)}")
        print(f"Rank mismatches: {len(rank_mismatches)}")
        print(f"Unbolded target words: {len(unbolded)}")
        print()
        print(f"Cards to create: {len(entries) * 2}")
        if args.llm == "ollama":
            print(f"LLM backend requested: ollama ({args.llm_model} @ {args.llm_host})")
        else:
            print("LLM backend: none (no usage notes will be generated)")
        return

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # --- Audio stage ---------------------------------------------------------
    media_files: list[str] = []
    failures: list[tuple[str, str, str]] = []
    if args.no_audio:
        for entry in entries:
            entry["audio_tag"] = ""
            entry["example_audio_tag"] = ""
            entry["example_audio_slow_tag"] = ""
        print("Audio generation skipped (--no-audio).")
    else:
        engine = pick_tts_engine(args.tts_engine)
        check_audio_dependencies(engine)
        voice = resolve_voice(engine, args.voice)
        normal_rate, slow_rate = resolve_speeds(args, engine)
        print(f"Generating audio with {engine}, voice {voice} "
              f"(normal={normal_rate!r}, slow={slow_rate!r}) ...")

        def audio_progress(i: int, n: int, word: str) -> None:
            print(f"  Audio {i}/{n}: {word}")

        media_files, failures = add_audio_to_entries(
            entries, Path(args.cache_dir), engine=engine, voice=voice,
            normal_rate=normal_rate, slow_rate=slow_rate,
            edge_pitch=args.edge_pitch, rhvoice_pitch=args.rhvoice_pitch,
            mp3_bitrate=args.mp3_bitrate,
            edge_retries=args.edge_retries, edge_retry_delay=args.edge_retry_delay,
            use_cache=not args.no_cache,
            progress=audio_progress,
        )

        n_word = sum(1 for e in entries if e.get("audio_tag"))
        n_sentence = sum(1 for e in entries if e.get("example_audio_tag"))
        n_slow = sum(1 for e in entries if e.get("example_audio_slow_tag"))
        total = len(entries)
        print()
        print("Audio generation")
        print("-----------------")
        print(f"Word audio:           {n_word}/{total}")
        print(f"Example audio:        {n_sentence}/{total}")
        print(f"Slow example audio:   {n_slow}/{total}")
        if failures:
            print()
            print("Failed audio:")
            for rank, word, clip_type in failures[:30]:
                print(f"  #{rank} {word} ({clip_type})")
            if len(failures) > 30:
                print(f"  ... and {len(failures) - 30} more (see the failed-audio log)")
            failed_log_path = Path(args.failed_log) if args.failed_log else (
                output_path.with_name(output_path.stem + ".failed.txt")
            )
            write_failed_log(failed_log_path, failures)
            print(f"Full list written to {failed_log_path}")

    # --- LLM stage -----------------------------------------------------------
    llm_failures: list[tuple[str, str, str]] = []
    if args.llm == "ollama":
        print()
        print(f"Generating usage notes with {args.llm_model} via Ollama at {args.llm_host} ...")
        check_ollama_available(args.llm_host, args.llm_model)

        def llm_progress(i: int, n: int, word: str) -> None:
            print(f"  Note {i}/{n}: {word}")

        llm_failures = generate_usage_notes(
            entries,
            cache_dir=Path(args.llm_cache_dir),
            model=args.llm_model,
            host=args.llm_host,
            prompt_version=args.llm_prompt_version,
            timeout=args.llm_timeout,
            temperature=args.llm_temperature,
            max_tokens=args.llm_max_tokens,
            use_cache=not args.no_llm_cache,
            progress=llm_progress,
        )

        n_notes = sum(1 for e in entries if e.get("usage_note"))
        total = len(entries)
        print()
        print("Usage notes")
        print("-----------")
        print(f"Notes generated:      {n_notes}/{total}")
        print(f"Notes failed:         {len(llm_failures)}")
        if llm_failures:
            print()
            print("Failed notes (first 30):")
            for rank, word, reason in llm_failures[:30]:
                # Trim long reason strings for the terminal summary.
                reason_short = reason.splitlines()[0] if reason else "(no reason)"
                print(f"  #{rank} {word} ({reason_short[:70]})")
            if len(llm_failures) > 30:
                print(f"  ... and {len(llm_failures) - 30} more (see the failed-notes log)")
            llm_failed_log_path = Path(args.llm_failed_log) if args.llm_failed_log else (
                output_path.with_name(output_path.stem + ".llm_failed.txt")
            )
            write_llm_failed_log(llm_failed_log_path, llm_failures)
            print(f"Full list written to {llm_failed_log_path}")
    else:
        # Explicitly blank so the field exists on every entry and the CSV
        # column is populated (with empty strings).
        for entry in entries:
            entry.setdefault("usage_note", "")

    # --- Build and write -----------------------------------------------------
    deck = build_deck(entries, args.deck_name)
    genanki.Package(deck, media_files=media_files).write_to_file(str(output_path))

    print(f"\nWrote {args.output}")
    if args.csv:
        write_csv(entries, args.csv)
        print(f"Wrote {args.csv}")


# --- Self-tests --------------------------------------------------------------

def _run_self_tests() -> int:
    """Minimal built-in test suite. Returns process exit code.

    Covers the parsing heuristics and cache-key stability.  No PDF, no
    network, no ffmpeg, no Ollama required.
    """
    tests: list[tuple[str, Callable[[], None]]] = []

    def case(name: str):
        def deco(fn):
            tests.append((name, fn))
            return fn
        return deco

    @case("classify_word: russian")
    def _():
        assert classify_word("привет") == "ru"

    @case("classify_word: english")
    def _():
        assert classify_word("hello") == "en"

    @case("classify_word: neutral punctuation")
    def _():
        assert classify_word("...") == "neutral"
        assert classify_word("123") == "neutral"

    @case("split_bilingual: long merged line")
    def _():
        ru, en = split_bilingual_line(
            "Я могу зайти завтра, если хочешь.    I can drop by tomorrow if you want."
        )
        assert ru == "Я могу зайти завтра, если хочешь."
        assert en == "I can drop by tomorrow if you want."

    @case("split_bilingual: short both-terminal")
    def _():
        ru, en = split_bilingual_line("Да.   Yes.")
        assert ru == "Да."
        assert en == "Yes."

    @case("split_bilingual: single-language line returns None")
    def _():
        ru, en = split_bilingual_line("Вчера она купила фрукты и овощи.")
        assert ru is None and en is None

    @case("bold_word_in_sentence: exact match")
    def _():
        out = bold_word_in_sentence("Книга лежит на столе.", "на")
        assert "<b>на</b>" in out

    @case("bold_word_in_sentence: HTML-safe")
    def _():
        out = bold_word_in_sentence("a < b & c > d", "b")
        # The b word should not appear raw; the sentence should be escaped.
        assert "&lt;" in out and "&amp;" in out

    @case("bold_word_in_sentence: inflected form not bolded")
    def _():
        out = bold_word_in_sentence("Он поднял руку.", "рука")
        assert "<b>" not in out

    @case("strip_tags: removes b tags")
    def _():
        assert strip_tags("a <b>b</b> c") == "a b c"

    @case("strip_tags: handles stray angle brackets")
    def _():
        # Should not raise, and should not lose the trailing text.
        out = strip_tags("x < y > z")
        assert "x" in out and "z" in out

    @case("cache_key_for: changes when text changes")
    def _():
        a = cache_key_for("edge", "v", "+0%", "+0Hz", "hello")
        b = cache_key_for("edge", "v", "+0%", "+0Hz", "world")
        assert a != b

    @case("cache_key_for: stable for same input")
    def _():
        a = cache_key_for("edge", "v", "+0%", "+0Hz", "hello")
        b = cache_key_for("edge", "v", "+0%", "+0Hz", "hello")
        assert a == b

    @case("cache_key_for: changes when voice changes")
    def _():
        a = cache_key_for("edge", "v1", "+0%", "+0Hz", "hello")
        b = cache_key_for("edge", "v2", "+0%", "+0Hz", "hello")
        assert a != b

    @case("llm_cache_key_for: prompt version bumps key")
    def _():
        a = llm_cache_key_for("m", "1", "и", "and")
        b = llm_cache_key_for("m", "2", "и", "and")
        assert a != b

    @case("llm_cache_key_for: ignores example sentence")
    def _():
        # Same (model, prompt_version, word, translation) -> same key,
        # regardless of anything else.
        a = llm_cache_key_for("m", "1", "и", "and")
        b = llm_cache_key_for("m", "1", "и", "and")
        assert a == b

    @case("_sanitize_usage_note: strips bold markdown")
    def _():
        out = _sanitize_usage_note("This is **bold** text.")
        assert "**" not in out
        assert "bold" in out

    @case("_sanitize_usage_note: strips bullet prefix")
    def _():
        out = _sanitize_usage_note("- first point\n- second point")
        assert not out.startswith("-")
        assert "first point" in out

    @case("_sanitize_usage_note: caps length")
    def _():
        out = _sanitize_usage_note("word " * 500)
        assert len(out) <= 400
        assert out.endswith("...")

    @case("_sanitize_usage_note: collapses whitespace")
    def _():
        out = _sanitize_usage_note("a    b\n\nc")
        assert out == "a b c"

    @case("resolve_speeds: edge --speed override produces rate string")
    def _():
        # Fake a minimal namespace.
        class NS:
            speed = 75
            slow_speed = None
            edge_rate = "+0%"
            slow_rate = "-50%"
            rhvoice_rate = 100
            tts_speed = 140
        normal, slow = resolve_speeds(NS(), "edge")
        assert normal == "-25%"
        assert slow == "-50%"

    @case("resolve_speeds: espeak slow never faster than normal")
    def _():
        class NS:
            speed = None
            slow_speed = None
            edge_rate = "+0%"
            slow_rate = "-50%"
            rhvoice_rate = 100
            tts_speed = 30   # pathologically slow
        normal, slow = resolve_speeds(NS(), "espeak")
        assert slow < normal

    failed = 0
    for name, fn in tests:
        try:
            fn()
            print(f"PASS  {name}")
        except AssertionError as exc:
            failed += 1
            print(f"FAIL  {name}: {exc}")
        except Exception as exc:  # noqa: BLE001
            failed += 1
            print(f"ERROR {name}: {type(exc).__name__}: {exc}")

    total = len(tests)
    print()
    print(f"{total - failed}/{total} tests passed")
    return 1 if failed else 0


# --- Entry point -------------------------------------------------------------

if __name__ == "__main__":
    try:
        main()
    except ConversionError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        sys.exit(130)

